# Generated by Django 4.0.5 on 2023-01-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katha_no', models.CharField(max_length=50)),
                ('passbook_no', models.CharField(max_length=50)),
                ('document_no', models.CharField(max_length=100, unique=True)),
                ('aadhar_no', models.BigIntegerField(unique=True)),
                ('pass_photo', models.ImageField(upload_to='api/images/pass_photos')),
                ('passbook_photo', models.ImageField(upload_to='api/images/passbook_photos')),
                ('note', models.TextField(help_text='enter text here', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_photos', models.FileField(upload_to='api/images/documents')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.document_details')),
            ],
        ),
        migrations.CreateModel(
            name='post_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_images', models.ImageField(upload_to='api/images/document_images')),
                ('document_files', models.FileField(blank=True, null=True, upload_to='api/files')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.document_details')),
            ],
        ),
        migrations.CreateModel(
            name='PlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=20)),
                ('land_extent', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.new_project')),
            ],
        ),
        migrations.CreateModel(
            name='PlotAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_amount', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_nos', to='api.document_details')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.new_project')),
            ],
        ),
        migrations.CreateModel(
            name='New_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=100)),
                ('mobile_number', models.BigIntegerField(unique=True, verbose_name='mobile number')),
                ('survey_no', models.CharField(max_length=50)),
                ('land_extent', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('community', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana')], max_length=50)),
                ('pincode', models.PositiveSmallIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.new_project')),
            ],
        ),
        migrations.AddField(
            model_name='document_details',
            name='plot_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_nos', to='api.new_registration'),
        ),
        migrations.AddField(
            model_name='document_details',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.new_project'),
        ),
    ]
